### ISSUE TITLE
登录不上

### ISSUE THREAD

**Issue by ahtoh84** [shuiRong/Gakki#1]
作者你好，在登录界面输入域名后，点击登录就没反应了，返回的话会一直卡在loading界面。

**Comment by shuiRong** [comment]
忘记说明了，如果你登陆的实例（比如cmx.im）需要翻墙的话，那么你手机就也需要翻墙才能正常使用（否则接口会拉不到数据）

**Comment by shuiRong** [comment]
@ahtoh84 
如果再遇到问题的话，在这里大声喊我，我再重新开启issue。先关闭了。
