### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by tokpig** [shuiRong/Gakki#2]
登陆mastodon这个按钮无效！

**Comment by shuiRong** [comment]
因为cmx.im实例已经被墙，因此在App端登录的时候需要先翻墙。
你有翻墙吗？

**Comment by shuiRong** [comment]
长时间没有回应，先关掉了。如果还有问题的话，再喊我

**Comment by shuiRong** [comment]
长时间没有回应，先关掉了。如果上面说的方法无效，再喊我
