### ISSUE TITLE
Please increase versionCode with each release

### ISSUE THREAD

**Issue by IzzySoft** [shuiRong/Gakki#5]
All your releases seem to keep their `versionCode` at `1`. As that's the value Android tells different versions of an app apart from each other, it should be increased with each release – otherwise Android complains that version is already installed. So could you please remember increasing that whenever you make a new release? Thanks in advance!

While on it: is there an English description for the app somewhere – for folks outside China?

**Comment by shuiRong** [comment]
Thanks for reminding! It's an error, I will remember it.

English description will be published as soon as possible.

**Comment by IzzySoft** [comment]
Thanks a lot! Looking forward to it :smiley:

**Comment by shuiRong** [comment]
@IzzySoft  hey friend, Documentation still needs more details to help run the project correctly.（I am testing and then will remind you）

**Comment by IzzySoft** [comment]
Thanks! OK, disclosure:

I'm myself am a happy Tusky user. But I run different Android related "services". There's e.g. my [Android App Lists](https://android.izzysoft.de/applists) to help users finding the app suiting them for the purpose they need one – and there's my [F-Droid compatible app repo](https://apt.izzysoft.de/fdroid) for apps that cannot (yet) be included with the [official one](https://f-droid.org/) for some reason (so it's like a mix of Debian nonfree and testing). Not being an Android dev myself, that's how I contribute to the open source community.

I could include your app in one or both of those places, maybe. So I look forward to your updates!

**Comment by shuiRong** [comment]
The final ( I hope so :p ) documentation was just published. Any developer can follow it and run Gakki in their computer. (If you are not a Front-End developer, It may be tough...)

Your website is so cool and the people who contribute to the open source community is cool also.

This is the second time I have heard F-Droid. It seems that I have to google what it is.

**Comment by IzzySoft** [comment]
No need to involve a data collector (Google) with that. Start here, with part 1 of my blog series on F-Droid: [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1). Other parts are linked from there (currently 3, a 4th is "in-the-make").

Thanks for the translation! And right, I'm not an Android dev at all. But for end-users, you provide the APK in `releases/` – so I was hoping for a short description of the app itself. Currently, all I can tell is it's a Mastodon client. With the screenshots bein in Chinese, I cannot tell what's in the menu – and only guess some features. So from the end-user's view, a short description with a list of the main features would be great. Then, with the next APK(s) having the correct versionCode, I could go ahead and list it. It's hard at the size limit for my repo (which is 20M per app), but still fits – and when my library scanner shows "all green" (i.e. no proprietary components), I could help you bring the app into the official repo (provided there are also no "blobs" like JAR files involved in your code – which we then would need to have substitute by their source or pulling from a trusted maven repo – we can see to that then).

**Comment by shuiRong** [comment]
ok, I'll append more information on the documentation. and that's awesome if Gakki can be brought into the F-Droid in the future. Of course, it needs to pass all the tests, I will adjust my code if necessary.

**Comment by IzzySoft** [comment]
Thanks! Please give me a ping when I shall check again.

**Comment by IzzySoft** [comment]
OK, got that ping :rofl: Added your app to my repo (should show up [here](https://apt.izzysoft.de/fdroid/index/apk/com.gakki) in about 2..3 hours from now, with the next sync – feel free to add a link to your readme and point out it can be installed and kept up-to-date using the F-Droid client).

Looks good so far, according to my scanner. One possible issue I see is CodePush: is that really completely open, or does it need some component only available as binary? A quick glance into the repo didn't reveal any, and even the `android/app/build.gradle` looks fine, including the Maven repos used. So if you wish, we could make a try for the official repo straight away. You can [open an RFP](https://gitlab.com/fdroid/rfp/issues) yourself if you have a GitLab account, or I can do that for you. Just let me know what it should be, and I gladly assist.

**Comment by shuiRong** [comment]
@IzzySoft 
got it and thanks for your work.

I think I better remove `CodePush` in the next version because It's not allowed also by Google Play(I will publish Gakki on there after I apply for a visa credit card  :p )

What should I do about updating Gakki in F-Droid after I publish a new version?

**Comment by IzzySoft** [comment]
For my repo: add a new tag and attach the APK to it. For the official repo (once your app has applied for it and got listed), just add a new tag (APK will be built from source). In both cases, don't forget increasing `versionCode` and adjusting `versionName`.

Good idea to drop CodePush (let me know when done so I check if the `NonFreeNet` AntiFeature can be removed). There are ways for "free" notifications, e.g. Tutanota uses something in this regard (I'm not a dev, so I didn't dig into that).

**Comment by shuiRong** [comment]
@IzzySoft Hey, I removed CodePush already. 
You can check it and update the version on F-Droid. The newest APK file is [here](https://github.com/shuiRong/Gakki/releases/tag/v1.1.6).
Thank you in advance.

**Comment by IzzySoft** [comment]
@shuiRong sorry, forgot to update here: the new version was fetched automatically by my updater – and my library scanner confirms CodePush being gone. Which reminds me: from what the remaining libraries show, I should remove the `NonFreeNet` AntiFeature. I hope I remember that when being back home (I somehow have missed the Github notification mail)…

**Comment by shuiRong** [comment]
@IzzySoft That's great. Thanks for your work~

**Comment by IzzySoft** [comment]
Gladly! Update went live last night.
